### ISSUE TITLE
imagemagick

### ISSUE THREAD

**Issue by stfu23489** [WintrCat/autoshorts#2]
Spawning Python process...
Traceback (most recent call last): File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\VideoClip.py", line 1137, in __init__
subprocess_call(cmd, logger=None) File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\tools.py", line 46, in subprocess_call proc = sp.Popen(cmd, **popen_params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [WinError 2] The system cannot find the file specified During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\Users\[username]\OneDrive\Documents\autoshorts-master\src\lib\python\trivia.py", line 156, in produce_short( File "C:\Users\[username]\OneDrive\Documents\autoshorts-master\src\lib\python\trivia.py", line 63, in produce_short editor.TextClip( File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\VideoClip.py", line 1146, in __init__
raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error: [WinError 2] The system cannot find the file specified. .This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Comment by WintrCat** [comment]
You need to have ImageMagick installed on your device, which is what the error suggests.

**Comment by riverpaper** [comment]
@stfu23489, I spent like an hour or two trying to fix that one error.

You have to install ImageMagick or download the portable version. [Download for all platforms here](https://imagemagick.org/script/download.php), but I got Windows 64x portable. Note that for the portable version, you have to extract the `.zip` file to a folder.

---

Afterwards, you have to configure moviepy to recognise ImageMagick's install location. Specifically, moviepy needs to know where `magick.exe` is located. There are multiple ways to do this.

Normally, you'd add your ImageMagick installation directory to your global `PATH` variable, but I couldn't get it to work. Instead, I edited my installation of moviepy (specifically [line 22 in `[/moviepy]/config.py`](https://github.com/Zulko/moviepy/blob/master/moviepy/config.py#L22)) to look directly where I downloaded ImageMagick. It looks like this:

```py
# before
IMAGEMAGICK_BINARY = os.getenv("IMAGEMAGICK_BINARY", "auto-detect")

# after
IMAGEMAGICK_BINARY = os.getenv("IMAGEMAGICK_BINARY", r"C:\path\to\magick.exe")
```

---

With that, ImageMagick should be installed and configured correctly. I did end up getting more errors after this one, specifically with something calling the `Image.ANTIALIAS` attribute, which apparently doesn't exist in my installation.

```
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

> Actually, this was fixed in this commit: https://github.com/Zulko/moviepy/commit/e163cf53a4d9d82a5697ee8d02099f91dc241cc9
> 
> It should work as of `moviepy-1.0.3`, but I'm not sure.

If you do get this error, you need to replace `Image.ANTIALIAS` with `Image.Resampling.LANCZOS` in your moviepy installation (specifically in [`[/moviepy]/video/fx/resize.py`](https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/resize.py)).

---

That should be all, but if you need any more help, please ask! I don't want anyone to ever go through what I went through. At least now I can make phonk chess shorts!

---

@WintrCat, I think you should include a bit of a guide for this. Some of your YouTube audience will come here without having used NPM before (including me, even though I code and stuff). This project uses a weird combination of tools (TypeScript + Python + Stockfish + etc.), making it prone to unpredictable errors, as shown above. I think it's best to guide the user through the setup process in a case like this.

**Comment by riverpaper** [comment]
@WintrCat 

> You need to have ImageMagick installed on your device

Even with ImageMagick installed, you have to either:

- configure ImageMagick to be findable in the system path (which I don't think the installer has an option for, and thus must be done manually), or
- configure moviepy to find ImageMagick where it's installed (which requires modifying your moviepy installation within your Python installation).

I would guess that you did the first one, and so you didn't think it would be a problem for others.

I love when YouTubers make projects like this, then release their code to the audience. This only becomes a problem when other people can't run the code. It turns what would be a "showcase video" into a "showcase video + tutorial", which increases the effort the creator has to put in, like what's happening here.

Of course, this is no-one's fault or anything; it's just how software development works. It just that creators sometimes don't realise that they're crossing the line from "video creation about software" to "active software support".

In any case, thank you for making this and releasing it to the public (and then for taking the time to reply to people's issues). I've had fun learning how PGN chess notation works, along with solving all the little challenges trying to make this run on my school computer that has so many restrictions...

Also, thank you for the time and effort you've put into growing your community. ✌️

**Comment by WintrCat** [comment]
Hi @silvncr, thanks for taking an interest my project mate 🙂

Admittedly, I probably didn't go into enough detail with my answer on how to get ImageMagick running, so thank you for writing a better response haha.

When I installed ImageMagick for myself, I also had to configure moviepy directly to point it towards the ImageMagick binary. You can read [this page of the moviepy documentation](https://zulko.github.io/moviepy/install.html#other-optional-but-useful-dependencies) where it's documented officially that on Windows systems, you need to do this annoying configuration thing rather than simply adding it to the system path. Nonetheless, when I get time I will write a small section of the README to help people with this installation!

The source code is available mostly as an addition to the video for transparency's sake, and I don't promise anyone that they'll be able to deploy it without at least some prior experience in the tooling that's been used. While I try to help as much as I can, unfortunately I don't guarantee any software support.

Thanks 👍

**Comment by riverpaper** [comment]
> Thank you for writing a better response haha

I found this issue right after I got it running, and I wanted to document the solution while it was all fresh in my mind.

> It's documented officially that on Windows systems, you need to [...]

Oh wow, I didn't realise that; I thought I'd found a workaround.

> when I get time I will write a small section of the README to help people

Feel free to copy some of what I wrote if you want; I'm sure you're busy. /gen

Just keep in mind that from my perspective, I just bodged it together, so my solution might not exactly be "best practice".

> The source code is available mostly as an addition to the video for transparency's sake, and I don't promise anyone that they'll be able to deploy it without at least some prior experience in the tooling that's been used. While I try to help as much as I can, unfortunately I don't guarantee any software support.

That totally makes sense. Thank you!
